version: '3.7'
services:
  db:
    image: postgres:15
    container_name: game_shop_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: game_shop_cache

  game_shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_shop_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command:
      - "docker/app.sh"
    ports:
      - 7777:8000
