global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'game_shop'

    scrape_interval: 5s

    static_configs:
      - targets: [ "game_shop:8000" ]