"""Users role_id - nullable=True

Revision ID: 2b9b6c2e8723
Revises: e05eb5fe95e7
Create Date: 2023-11-18 01:12:06.684873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9b6c2e8723'
down_revision: Union[str, None] = 'e05eb5fe95e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
