"""Goods name is unique

Revision ID: 7fbf0bf7d4b5
Revises: e05eb5fe95e7
Create Date: 2023-11-19 01:34:42.571454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7fbf0bf7d4b5'
down_revision: Union[str, None] = 'e05eb5fe95e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'goods', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    # ### end Alembic commands ###
